language: minimal

sudo: required
services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build . -t vsuzdaltsev/ruby-aws-sdk

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vsuzdaltsev/ruby-aws-sdk:latest
